### ISSUE TITLE
explode parameter 2 & Hash errors

### ISSUE THREAD

**Issue by linkingarts** [CakePHP-Bootstrap/cakephp2-bootstrap2-helpers#1]
I've set up in AppController:

```
public $helpers = array(
    'Html' => array(
        'className' => 'BootstrapHtml'
    ),
    'Form' => array(
        'className' => 'BootstrapForm'
    ),
    'Paginator' => array(
        'className' => 'BootstrapPaginator'
    ),
```

...

For each field I get a ton of errors:

Warning (2): explode() expects parameter 2 to be string, array given [CORE/Cake/View/Helper.php, line 491]

Warning (4096): Argument 1 passed to Hash::filter() must be an array, null given, called in /Volumes/www/www.wedocracy.com/lib/Cake/View/Helper.php on line 491 and defined [CORE/Cake/Utility/Hash.php, line 488]

Warning (2): Invalid argument supplied for foreach() [CORE/Cake/Utility/Hash.php, line 489]

Warning (2): array_filter() expects parameter 1 to be array, null given [CORE/Cake/Utility/Hash.php, line 494]

Warning (2): array_values() expects parameter 1 to be array, null given [CORE/Cake/View/Helper.php, line 491]

Notice (8): Array to string conversion [APP/View/Helper/BootstrapFormHelper.php, line 191]

Warning (2): array_merge() [http://php.net/function.array-merge]: Argument #3 is not an array [CORE/Cake/View/Helper/FormHelper.php, line 935]

Warning (2): explode() expects parameter 2 to be string, array given [CORE/Cake/View/Helper.php, line 491]

Warning (4096): Argument 1 passed to Hash::filter() must be an array, null given, called in /Volumes/www/www.wedocracy.com/lib/Cake/View/Helper.php on line 491 and defined [CORE/Cake/Utility/Hash.php, line 488]

Warning (2): Invalid argument supplied for foreach() [CORE/Cake/Utility/Hash.php, line 489]

Warning (2): array_filter() expects parameter 1 to be array, null given [CORE/Cake/Utility/Hash.php, line 494]

Warning (2): array_values() expects parameter 1 to be array, null given [CORE/Cake/View/Helper.php, line 491]

Notice (8): Undefined index: before [CORE/Cake/View/Helper/FormHelper.php, line 1076]

Notice (8): Undefined index: between [CORE/Cake/View/Helper/FormHelper.php, line 1076]

Notice (8): Undefined index: after [CORE/Cake/View/Helper/FormHelper.php, line 1076]

Notice (8): Undefined index: format [CORE/Cake/View/Helper/FormHelper.php, line 1079]

Warning (2): explode() expects parameter 2 to be string, array given [CORE/Cake/View/Helper.php, line 491]

Warning (4096): Argument 1 passed to Hash::filter() must be an array, null given, called in /Volumes/www/www.wedocracy.com/lib/Cake/View/Helper.php on line 491 and defined [CORE/Cake/Utility/Hash.php, line 488]

Warning (2): Invalid argument supplied for foreach() [CORE/Cake/Utility/Hash.php, line 489]

Warning (2): array_filter() expects parameter 1 to be array, null given [CORE/Cake/Utility/Hash.php, line 494]

Warning (2): array_values() expects parameter 1 to be array, null given [CORE/Cake/View/Helper.php, line 491]

**Comment by Holt59** [comment]
Are you sure you are using CakePHP >= 2.3 ? I haven't modified the files specified in your warning messages, so I'm not sure they are coming from my helpers... If you can give more details about your configuration, I'll be able to check it.
