### ISSUE TITLE
Do not stylized input of type "password"

### ISSUE THREAD

**Issue by innovaweb-dev** [CakePHP-Bootstrap/cakephp2-bootstrap2-helpers#3]
Hello and Happy New Year too,

Is someone the same problem as me?
The input of type "password" are not stylize.

Thank you,

**Comment by Holt59** [comment]
Are  you sure this is the right repository? This plugin is for CakePHP 2.x with **bootstrap 2**.

**Comment by innovaweb-dev** [comment]
Oops, sorry.
That's Bootstrap 3.x, I move the topic.

**Comment by innovaweb-dev** [comment]
https://github.com/Holt59/cakephp-bootstrap3-helpers/issues/12
